### ISSUE TITLE
Problem with the import command

### ISSUE THREAD

**Issue by anantk007** [pulse-vadc/terraform-provider-vtm#1]
Hello,
Not sure if I am doing something wrong here.

I am trying to import a rule into the terraform state from a traffic manager configuration that has happened outside of terraform control.

The rule name on the traffic manager is "TestRule1"

So as per the instructions I have added a block to my main.tf which will be a meathook for the incoming configuration.

resource "vtm_rule" "trule1"
{
  name = "TestRule1"
  content = <<EOF
             EOF
}

After this I run the following command.
terraform import vtm_rule.trule1 TestRule1

Error that I get:

[root@docker software]# /software/terraform import vtm_rule.trule1 TestRule1
vtm_rule.trule1: Importing from ID "TestRule1"...
vtm_rule.trule1: Import complete!
  Imported vtm_rule (ID: TestRule1)
vtm_rule.trule1: Refreshing state... (ID: TestRule1)

Error: vtm_rule.trule1 (import id: TestRule1): 1 error(s) occurred:

* import vtm_rule.trule1 result: TestRule1: import vtm_rule.trule1 (id: TestRule1): Terraform detected a resource with this ID doesn't
exist. Please verify the ID is correct. You cannot import non-existent
resources using Terraform import.

**Comment by mgeldert** [comment]
Thank you for reporting this issue.  We are currently investigating, but what you have attempted to do looks to be correct, so we suspect the cause lies in the provider implementation.  We will update this issue as soon as we have progress to report.

**Comment by mgeldert** [comment]
We've now isolated the issue and will be releasing the fix in the very near future.  Thank you for your patience.

**Comment by lewissw** [comment]
Hi @mgeldert any news on when this fix will be available? @anantk007 is dying to test it out :-)
Thanks
Steve

**Comment by mgeldert** [comment]
@anantk007 @lewissw Apologies for the delay.  I have now updated the source code and the release binaries with the fix.  Please let us know how you get on with them.

**Comment by anantk007** [comment]
@mgeldert @lewissw 
Hello,
I have now tested the import command with basic components like rules, virtual servers , pools and global settings and it seems to work OK.

Thanks for providing the fix.

**Comment by anantk007** [comment]
Ok to close this issue now.
