### ISSUE TITLE
Syntax check for rules , in terraform

### ISSUE THREAD

**Issue by iahmad-khan** [pulse-vadc/terraform-provider-vtm#12]
In Web UI , we can do syntax check before updating a rule , is there something available in terraform provider? or it will auto fail during apply if there is problem in rule syntax? or is there a vtm rule linter we can run before terraform apply.

**Comment by ndavidson-pulse** [comment]
We currently don't do a syntax check of rules before application with the terraform provider.

**Comment by iahmad-khan** [comment]
@ndavidson-pulse is there a command line VTM rule linter that we can run before running terraform?

**Comment by iahmad-khan** [comment]
Can we request it as feature? because even if there is existing command line linter  for checking rules, it wont work with terraform style code.

**Comment by ndavidson-pulse** [comment]
You can lint rules from the commandline with the zeus.zxtm binary - see --help for details.

**Comment by ndavidson-pulse** [comment]
We've already got an internal request for enhancement for the REST API part of the functionality - if you contact me at <my github username without -pulse> at pulsesecure dot net with some customer details I'll make sure you are added to the issue.
