### ISSUE TITLE
Terraform 0.12 and VTM provider

### ISSUE THREAD

**Issue by lewissw** [pulse-vadc/terraform-provider-vtm#14]
Do you have any plans to support the new release of terraform?

terraform 0.12upgrade

This command will rewrite the configuration files in the given directory so
that they use the new syntax features from Terraform v0.12, and will identify
any constructs that may need to be adjusted for correct operation with
Terraform v0.12.

We recommend using this command in a clean version control work tree, so that
you can easily see the proposed changes as a diff against the latest commit.
If you have uncommited changes already present, we recommend aborting this
command and dealing with them before running this command again.

Would you like to upgrade the module in the current directory?
  Only 'yes' will be accepted to confirm.

  Enter a value: yes

-----------------------------------------------------------------------------

Error: failed to load provider "vtm": Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

**Comment by ndavidson-pulse** [comment]
Yep, we intend to support it we're just discussing internally when we'll schedule the work. We haven't discussed what support will look like, and it would be useful to get some community feedback on the issue. 

We're likely to simply move all supported versions of the Traffic Manager terraform provider to 0.12 in a future release and those who wish to continue using 0.11 can use an older release of our providers.

**Comment by kizzie** [comment]
Heya! Just wondering if you had any progress on this one? Keen to get everything updated to 0.12.x as soon as possible :)

**Comment by ndavidson-pulse** [comment]
Hi Kizzie, we've internal builds using terraform  0.12 and we're planning to roll a single 19.1 release for the provider with Terraform 0.12 support and provider versions for the vADC 19.1 and 19.2 releases fairly soon.

**Comment by ndavidson-pulse** [comment]
Fixed in VTMTF_19_1
