### ISSUE TITLE
Issue with 5.2.0

### ISSUE THREAD

**Issue by iahmad-khan** [pulse-vadc/terraform-provider-vtm#15]
I download and convert json to tfm format and when I push , terraform does some strange changes to text and names:

For example virtual_server log format string , T changes to lower case t:

```

 - "format": "%h %l %u %t '%r' %s %b '%{Referer}i' '%{User-agent}i' %n %T %{Host}i",
 + "format": "%h %l %u %t '%r' %s %b '%{Referer}i' '%{User-agent}i' %n %t %{Host}i",

```

Same for the note:

```json
    -  "note": "This name/IP only available internally",
    +  "note": "this name/IP only available internally",
```

The practical issue is with rule names though, so it changes the rule name to one that doesn't even exist:

```json
        -  "migration_add_X-HTTPS_header",
        +  "migration_add_X-HttPS_header",
```

Similarly:

```json
     "ocsp_issuers": [
        {
         -  "issuer": "_DEFAULT_",
         +  "issuer": "_DEfAULt_",
          "aia": true,
          "nonce": "off",
```

Why is it auto converting some random chars into lower case.

**Comment by ndavidson-pulse** [comment]
That's very weird - we'll investigate.

**Comment by iahmad-khan** [comment]
@ndavidson-pulse ok by changing the api version to 6.0 and getting the json from vtm-18.2 , I see that now its downloading those characters as lower case in first place. there is something wrong with api

**Comment by iahmad-khan** [comment]
For now , I am correcting them with sed replace , before pushing it back through tfm.

**Comment by ndavidson-pulse** [comment]
Sorry, I don't quite follow the explanation - are you saying the JSON response from the 5.2 API is different?

**Comment by ndavidson-pulse** [comment]
Did you see my comment on #16 - if you're mixing and matching the 5.2 API response with the 6.0 provider version stuff isn't going to work properly - you should make sure you use the 6.0 API version JSON  with the 6.0 provider to minimize issues.

**Comment by iahmad-khan** [comment]
No , I am now using the api version 6.0 with provider 6.0 , but when I try to download the json using api version 6.0 , the downloaded json has that issue of changing the characters

**Comment by pillalamarriramana** [comment]
5.2 is not relevant with 22.1 VTMTF Release.
