### ISSUE TITLE
vTM 19.1 support

### ISSUE THREAD

**Issue by rklabs** [pulse-vadc/terraform-provider-vtm#18]
Hello, 

I saw that [vTM 19.1](https://www-prev.pulsesecure.net/download/techpubs/current/1573/Pulse-vADC-Solutions/Pulse-Virtual-Traffic-Manager/19.1/ps-vtm-19.1-relnotes.pdf) has been released recently. Are there any plans to support this version in both vTM provider and [API](https://github.com/pulse-vadc/go-vtm). 

Thanks,
Raju Kadam

**Comment by ndavidson-pulse** [comment]
Hi Raju,

We should be releasing the 19.1 version of the terraform provider shortly.

**Comment by ndavidson-pulse** [comment]
And the API obviously.

**Comment by rklabs** [comment]
Awesome! Is there a release date, or approximate ETA?

**Comment by ndavidson-pulse** [comment]
Fixed in VTMTF_19_1
