### ISSUE TITLE
Old version of Terraform SDK causes panic during schema validation with nil values

### ISSUE THREAD

**Issue by imanran** [pulse-vadc/terraform-provider-vtm#23]
Hi,

Currently this provider is using the [Terraform v0.12.2](https://github.com/pulse-vadc/terraform-provider-vtm/blob/master/go.mod#L4) sdk.

If a nil value is passed for validation (in our case it was from a data source that was populating a list item) the provider attempts to use the sdk's schema validation which in turn tries to reflect a nil value causing a panic.

The [fix](https://github.com/hashicorp/terraform/pull/22236) for schema validation is available in the sdk starting with Terraform v0.12.6.

Please see if you can update to using the newer version of the Terraform SDK, or better yet switch to the [Terraform Plugin SDK](https://www.terraform.io/docs/extend/plugin-sdk.html) which has been the recommended route since September 2019.

**Comment by pillalamarriramana** [comment]
Used terraform sdk v0.12.20 with VTMTF 22.1 Release
