### ISSUE TITLE
Enabling/Disbaling of rules using vtm_rule_list datasource

### ISSUE THREAD

**Issue by anantk007** [pulse-vadc/terraform-provider-vtm#25]
Hello,
This method of querying a vtm_rule_list datasource provides a pretty neat way of picking and choosing rules from the complete rule inventory.

request_rules = ["${data.vtm_rule_list.my_rule_list.object_list}"]

However is there a way to control which rules are enabled or disabled on the VS with this method of association ?

**Comment by pillalamarriramana** [comment]
Closing this issue for now.
Please elaborate and re-open.
