### ISSUE TITLE
Terraform Provider Registry

### ISSUE THREAD

**Issue by alastairhm** [pulse-vadc/terraform-provider-vtm#26]
Hi,

Are you planning to submit your provider to the official [Terraform Provider Registry](https://registry.terraform.io/browse/providers)?

Even if it were submitted as a community provider, it would allow automatic installation of the provider, rather having to download then compile the provider.

Cheers,
Al

**Comment by alastairhm** [comment]
With Terraform 0.13 the setup of a local plugin custom/compiled providers has changed and introduces more complexity than the previous Terraform versions, being able to automatically install this from the Terraform registry would greatly reduce the setup of our GitlabCI Terraform pipelines.

**Comment by pillalamarriramana** [comment]
We have provided linux binaries with releases.
We are not exploring this at the moment.
