### ISSUE TITLE
Importing existing resources

### ISSUE THREAD

**Issue by iahmad-khan** [pulse-vadc/terraform-provider-vtm#4]
hi,

We are running three instnaces of vtm , and each of them have existing configurations , before starting to use this module to manage the vtm , we need to import all those exiting configs into teraform.

In terraform , there is a concept of importing existing resources , does this module support that? 

If not , is there any plan to add the import feature.

thanks

**Comment by mgeldert** [comment]
Hi @iahmad-khan,

Yes, I can confirm the import feature is supported.  Please let us know if you encounter any issues with the process.

Thanks,

Matt

**Comment by ndavidson-pulse** [comment]
Closing as no reported issues with the import function.
