### ISSUE TITLE
Virtual Server for DNS issue

### ISSUE THREAD

**Issue by lewissw** [pulse-vadc/terraform-provider-vtm#6]
Hi I'm having a problem configuring glb services:
vtm_virtual_server.vs_dns: Error creating vtm_virtual_server 'VS:DEV:TESTSERVICE:53': The resource provided is invalid ; basic_glb_services The value should be a space separated list of GLB Services.

The pdf says: 
The associated GLB serv
ices for this DNS virtual server.
•
Type: Set(String)
•Required: false
•
Default value: <none>

When using the provider, it wants me to pass a list for glb_services. If I enable debug on the api call to the traffic manager I can see:
\"basic\":{\"bandwidth_class\":\"\",\"completion_rules\":[],\"connect_timeout\":10,\"enabled\":true,\"glb_services\":[\"gms.btc-cce.bt.com\"]

i.e. the square brackets are wrapping the value.  

Am I missing something?
version info:
"terraform-provider-vtm_v6.0.0"
VTM Version is 18.2

**Comment by lewissw** [comment]
Sorry, can you close issue #6.
The VTM is giving a misleading error message. 
"invalid ; basic_glb_services The value should be a space separated list of GLB Services".  gets presented if the glb_service being referenced is disabled.

**Comment by ndavidson-pulse** [comment]
Hi lewissw - The problem appears to be that the  glb service doesn't exist by that name in the zxtm config. Have you made sure to specify a glb service in the terraform config? The resource dependencies should ensure it is created before the virtual server.

**Comment by lewissw** [comment]
Thanks

I don’t suppose you have a complete example of using TF to set up a DNS service?

Cheers

Steve

**Comment by dkalintsev** [comment]
Steve,

This may be able to help: https://github.com/dkalintsev/Terraform-vTM-GSLB
