### ISSUE TITLE
Issue with vtm_glb_service_location_settings_table

### ISSUE THREAD

**Issue by lewissw** [pulse-vadc/terraform-provider-vtm#7]
terraform version
_Terraform v0.11.11
+ provider.template v1.0.0
+ provider.tls v1.2.0
+ provider.vtm v6.1.0_

I have tried a number of times to populate a table for the GLB locations, this is a simplied one:

```
data "vtm_glb_service_location_settings_table" "mylocations_table" {
  # Repeat as many times as we have nodes in our node list variable
  count    = 1
  ips      = ["1.2.3.4"]
  //monitors = ["fred"]
  location = "Reigate-5"
  weight = 1
```
}

First error is:
```
Error: Error refreshing state: 15 error(s) occurred:

* module.vtm.data.vtm_glb_service_location_settings_table.mylocations_table: 1 error(s) occurred:

* module.vtm.data.vtm_glb_service_location_settings_table.mylocations_table: data.vtm_glb_service_location_settings_table.mylocations_table: unexpected EOF
```

Extract of DEBUG:
......
```
2019-01-04T12:00:37.177Z [DEBUG] plugin.terraform-provider-vtm_v6.1.0: goroutine 79 [running]:
2019/01/04 12:00:37 [TRACE] root.vtm: eval: *terraform.EvalReadState
2019-01-04T12:00:37.177Z [DEBUG] plugin.terraform-provider-vtm_v6.1.0: main.dataSourceGlbServiceLocationSettingsTableRead(0xc4201f8380, 0xfa0900, 0xc4202f4348, 0xc4201f8380, 0x0)
2019-01-04T12:00:37.177Z [DEBUG] plugin.terraform-provider-vtm_v6.1.0: 	/software/terraform-provider-vtm/6.1/data_source_table_glb_service_location_settings.go:60 +0x53c
2019-01-04T12:00:37.177Z [DEBUG] plugin.terraform-provider-vtm_v6.1.0: github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0xc4206f79d0, 0xc4206fb580, 0xfa0900, 0xc4202f4348, 0xc420266b20, 0xc42024f301, 0x80000000018)
```
....
Line 60 seems to be:
 ` Ips:      getStringListAddr(d.Get("ips").([]string)),
`
Any ideas where I'm going wrong?

Thanks

Steve

**Comment by ndavidson-pulse** [comment]
Hi Steve,

It's worth noting that a newer provider version will only work with a vTM new enough to support the API it expects, for example the 6.1 vTM provider must be used with at least vTM version 18.3 or newer. If you're using an older version of vTM please refer to the release page for compatibility details.

If you have a valid support contract with Pulse Secure then we can use that to exchange configuration and examples securely - but if you're happy to proceed via github then I'll need a little more information:

* What version of the vTM are you testing the provider against?
* Did your configuration work with an earlier version of the provider?

Regards,

Nick

**Comment by lewissw** [comment]
Hi, Thanks for getting back. I'm using the latest and greatest "Virtual Traffic Manager: Community Edition 18.3".  I couldn't get my HCL code to work with an older Terraform or the VTM 6.0.0 provider, so I upgraded everything to the latest and had the same failure. 

Thanks

Steve

**Comment by ndavidson-pulse** [comment]
Ok, I think I've reproduced your error - we're getting an unexpected panic from the terraform provider - I'll investigate a bit more on this end.

**Comment by ndavidson-pulse** [comment]
I have a candidate fix, I'm currently testing it and adding a test.

**Comment by ndavidson-pulse** [comment]
For your information this bug has been assigned an internal issue ID of VTMTF-126 which can be used to search for fix details in any new releases RELEASE_NOTES.txt

**Comment by ndavidson-pulse** [comment]
Fixed in VTMTF_19_1
